import type { Breed } from '../types'

// Curated starter set. Drives size/energy modifiers in the engine.
export const breeds: Breed[] = [
  {
    id: 'golden',
    name: 'Golden Retriever',
    size: 'large',
    energy: 'high',
    traits: ['Mouthy retriever', 'Loves water', 'Food motivated', 'Very trainable'],
    note: 'Slow to mature; expect a long adolescence.',
  },
  {
    id: 'labrador',
    name: 'Labrador Retriever',
    size: 'large',
    energy: 'high',
    traits: ['Mouthy', 'Food motivated', 'Loves water'],
  },
  {
    id: 'goldendoodle',
    name: 'Goldendoodle',
    size: 'large',
    energy: 'high',
    traits: ['Social', 'Mouthy', 'Smart'],
  },
  {
    id: 'german-shepherd',
    name: 'German Shepherd',
    size: 'large',
    energy: 'high',
    traits: ['High drive', 'Needs a job', 'Aloof with strangers'],
  },
  {
    id: 'boxer',
    name: 'Boxer',
    size: 'large',
    energy: 'high',
    traits: ['Playful', 'Slow to mature', 'Strong'],
  },
  {
    id: 'poodle',
    name: 'Poodle (Standard)',
    size: 'medium',
    energy: 'high',
    traits: ['Very smart', 'Loves to learn'],
  },
  {
    id: 'border-collie',
    name: 'Border Collie',
    size: 'medium',
    energy: 'high',
    traits: ['Extremely high drive', 'Needs serious mental work', 'Herding instinct'],
  },
  {
    id: 'australian-shepherd',
    name: 'Australian Shepherd',
    size: 'medium',
    energy: 'high',
    traits: ['Herding drive', 'High energy', 'Smart'],
  },
  {
    id: 'beagle',
    name: 'Beagle',
    size: 'small',
    energy: 'medium',
    traits: ['Nose-driven', 'Food motivated', 'Independent'],
  },
  {
    id: 'dachshund',
    name: 'Dachshund',
    size: 'small',
    energy: 'medium',
    traits: ['Independent', 'Prey drive'],
    note: 'Protect the long back: no repeated jumping on or off furniture.',
  },
  {
    id: 'cavalier',
    name: 'Cavalier King Charles Spaniel',
    size: 'small',
    energy: 'low',
    traits: ['Gentle', 'People-oriented'],
  },
  {
    id: 'french-bulldog',
    name: 'French Bulldog',
    size: 'small',
    energy: 'low',
    traits: ['Low stamina', 'Heat sensitive'],
    note: 'Keep sessions short and avoid heat; watch breathing during play.',
  },
  {
    id: 'mixed',
    name: 'Mixed or unknown',
    size: 'medium',
    energy: 'medium',
    traits: ['Varies'],
    note: 'Adjust the plan to the size and energy you actually see in your dog.',
  },
]
