import type { Breed } from '../types'

// Drives size/energy modifiers in the engine. Alphabetical; "Other / Mixed" last.
export const breeds: Breed[] = [
  {
    id: 'australian-shepherd',
    name: 'Australian Shepherd',
    size: 'medium',
    energy: 'high',
    traits: ['Herding drive', 'High energy', 'Smart'],
  },
  {
    id: 'beagle',
    name: 'Beagle',
    size: 'small',
    energy: 'medium',
    traits: ['Nose-driven', 'Food motivated', 'Independent'],
  },
  {
    id: 'belgian-malinois',
    name: 'Belgian Malinois',
    size: 'medium',
    energy: 'high',
    traits: ['Extreme drive', 'Needs a job', 'Not for first-time owners'],
    note: 'Exceptional working dog — needs structured training and serious mental work daily.',
  },
  {
    id: 'bernedoodle',
    name: 'Bernedoodle',
    size: 'large',
    energy: 'medium',
    traits: ['Gentle', 'Smart', 'May be stubborn'],
  },
  {
    id: 'bernese',
    name: 'Bernese Mountain Dog',
    size: 'large',
    energy: 'medium',
    traits: ['Gentle', 'Cold-weather breed', 'Slow to mature'],
    note: 'Slow to mature; expect a long adolescence.',
  },
  {
    id: 'bichon',
    name: 'Bichon Frise',
    size: 'small',
    energy: 'medium',
    traits: ['Gentle', 'Social', 'Trainable'],
  },
  {
    id: 'border-collie',
    name: 'Border Collie',
    size: 'medium',
    energy: 'high',
    traits: ['Extremely high drive', 'Needs serious mental work', 'Herding instinct'],
  },
  {
    id: 'boston-terrier',
    name: 'Boston Terrier',
    size: 'small',
    energy: 'medium',
    traits: ['Playful', 'Smart', 'Sensitive'],
  },
  {
    id: 'boxer',
    name: 'Boxer',
    size: 'large',
    energy: 'high',
    traits: ['Playful', 'Slow to mature', 'Strong'],
  },
  {
    id: 'cavalier',
    name: 'Cavalier King Charles Spaniel',
    size: 'small',
    energy: 'low',
    traits: ['Gentle', 'People-oriented'],
  },
  {
    id: 'chihuahua',
    name: 'Chihuahua',
    size: 'small',
    energy: 'medium',
    traits: ['Bold', 'Vocal', 'Can be reactive'],
  },
  {
    id: 'cocker-spaniel',
    name: 'Cocker Spaniel',
    size: 'medium',
    energy: 'medium',
    traits: ['Gentle', 'People-oriented', 'Sensitive to harsh corrections'],
  },
  {
    id: 'dachshund',
    name: 'Dachshund',
    size: 'small',
    energy: 'medium',
    traits: ['Independent', 'Prey drive'],
    note: 'Protect the long back: no repeated jumping on or off furniture.',
  },
  {
    id: 'doberman',
    name: 'Doberman Pinscher',
    size: 'large',
    energy: 'high',
    traits: ['High drive', 'Intelligent', 'Loyal', 'Needs a job'],
  },
  {
    id: 'french-bulldog',
    name: 'French Bulldog',
    size: 'small',
    energy: 'low',
    traits: ['Low stamina', 'Heat sensitive'],
    note: 'Keep sessions short and avoid heat; watch breathing during play.',
  },
  {
    id: 'german-shepherd',
    name: 'German Shepherd',
    size: 'large',
    energy: 'high',
    traits: ['High drive', 'Needs a job', 'Aloof with strangers'],
  },
  {
    id: 'gsp',
    name: 'German Shorthaired Pointer',
    size: 'large',
    energy: 'high',
    traits: ['Intense prey drive', 'Needs serious exercise', 'Field dog at heart'],
  },
  {
    id: 'golden',
    name: 'Golden Retriever',
    size: 'large',
    energy: 'high',
    traits: ['Mouthy retriever', 'Loves water', 'Food motivated', 'Very trainable'],
    note: 'Slow to mature; expect a long adolescence.',
  },
  {
    id: 'goldendoodle',
    name: 'Goldendoodle',
    size: 'large',
    energy: 'high',
    traits: ['Social', 'Mouthy', 'Smart'],
  },
  {
    id: 'great-dane',
    name: 'Great Dane',
    size: 'large',
    energy: 'medium',
    traits: ['Gentle giant', 'Slow to mature', 'Short stamina'],
    note: 'Growth plates close late; avoid high-impact exercise until 18–24 months.',
  },
  {
    id: 'havanese',
    name: 'Havanese',
    size: 'small',
    energy: 'medium',
    traits: ['Social', 'Trainable', 'People-oriented'],
  },
  {
    id: 'husky',
    name: 'Siberian Husky',
    size: 'large',
    energy: 'high',
    traits: ['Independent', 'Strong prey drive', 'Escape artist', 'High stamina'],
    note: 'Recall is very hard to train; keep on leash until rock-solid.',
  },
  {
    id: 'labradoodle',
    name: 'Labradoodle',
    size: 'large',
    energy: 'high',
    traits: ['Social', 'Mouthy', 'Smart', 'High energy'],
  },
  {
    id: 'labrador',
    name: 'Labrador Retriever',
    size: 'large',
    energy: 'high',
    traits: ['Mouthy', 'Food motivated', 'Loves water'],
  },
  {
    id: 'maltese',
    name: 'Maltese',
    size: 'small',
    energy: 'low',
    traits: ['Gentle', 'People-oriented'],
  },
  {
    id: 'mini-poodle',
    name: 'Miniature Poodle',
    size: 'small',
    energy: 'high',
    traits: ['Very smart', 'Loves to learn', 'Athletic'],
  },
  {
    id: 'mini-schnauzer',
    name: 'Miniature Schnauzer',
    size: 'small',
    energy: 'medium',
    traits: ['Smart', 'Independent', 'Vocal', 'Prey drive'],
  },
  {
    id: 'corgi',
    name: 'Pembroke Welsh Corgi',
    size: 'small',
    energy: 'medium',
    traits: ['Herding instinct', 'Vocal', 'Smart', 'Food motivated'],
  },
  {
    id: 'pomeranian',
    name: 'Pomeranian',
    size: 'small',
    energy: 'high',
    traits: ['Bold', 'Vocal', 'Smart'],
  },
  {
    id: 'poodle',
    name: 'Poodle (Standard)',
    size: 'medium',
    energy: 'high',
    traits: ['Very smart', 'Loves to learn'],
  },
  {
    id: 'pug',
    name: 'Pug',
    size: 'small',
    energy: 'low',
    traits: ['Food motivated', 'Heat sensitive', 'Stubborn'],
    note: 'Keep sessions short; watch breathing in heat.',
  },
  {
    id: 'rottweiler',
    name: 'Rottweiler',
    size: 'large',
    energy: 'high',
    traits: ['Loyal', 'Strong', 'Needs early socialization', 'Protective instinct'],
  },
  {
    id: 'sheepadoodle',
    name: 'Sheepadoodle',
    size: 'large',
    energy: 'high',
    traits: ['Playful', 'Mouthy', 'Smart'],
  },
  {
    id: 'shih-tzu',
    name: 'Shih Tzu',
    size: 'small',
    energy: 'low',
    traits: ['Gentle', 'People-oriented', 'Stubborn streak'],
  },
  {
    id: 'weimaraner',
    name: 'Weimaraner',
    size: 'large',
    energy: 'high',
    traits: ['Velcro dog', 'Prey drive', 'Needs a job', 'Separation anxiety prone'],
  },
  {
    id: 'yorkshire',
    name: 'Yorkshire Terrier',
    size: 'small',
    energy: 'medium',
    traits: ['Bold', 'Independent', 'Prey drive'],
  },
  {
    id: 'mixed',
    name: 'Other / Mixed breed',
    size: 'medium',
    energy: 'medium',
    traits: ['Varies'],
    note: 'Adjust the plan to the size and energy you actually see in your dog.',
  },
]
