import type { Command } from '../types'

// Seeded from The Good Dog Handbook command glossary.
export const commands: Command[] = [
  {
    id: 'name',
    name: 'Name',
    signal: '(none)',
    meaning: 'Look at me, pay attention.',
    core: true,
    category: 'foundation',
    prerequisites: [],
    teach: [
      'Say his name once. The instant he looks, mark "Yes" and treat.',
      'Do ten in a row, then say it when he is mildly distracted.',
      'Never repeat the name. If he does not look, make it easier.',
    ],
    mistake: 'Repeating his name. Say it once.',
  },
  {
    id: 'sit',
    name: 'Sit',
    signal: 'Flat hand, palm up, rising',
    meaning: 'Rear on the floor, held until released.',
    core: true,
    category: 'foundation',
    prerequisites: [],
    teach: [
      'Lure with a treat up and back over his head; his rear drops.',
      'Mark "Yes" as he lands it, treat, release "Done".',
      'Fade the lure within a few reps; pay from your pocket after.',
    ],
    mistake: 'Letting him pop up before the release.',
  },
  {
    id: 'down',
    name: 'Down',
    signal: 'Flat hand lowering to the floor',
    meaning: 'Lie all the way down and hold.',
    core: true,
    category: 'foundation',
    prerequisites: ['sit'],
    teach: [
      'Lure the treat to the floor and out; he follows into a down.',
      'Mark "Yes", treat between his paws, release "Done".',
      'Add the word once he is offering it easily.',
    ],
    mistake: 'Saying it three times.',
  },
  {
    id: 'stay',
    name: 'Stay',
    signal: 'Flat palm, "stop"',
    meaning: 'Hold this position until released.',
    core: false,
    category: 'foundation',
    prerequisites: ['sit', 'down'],
    teach: [
      'Build duration: count up the seconds he holds before you pay.',
      'Build distance: step back and return to him to pay.',
      'Always return to release calmly with "Done".',
    ],
    mistake: 'Releasing with the energy that makes him bolt.',
  },
  {
    id: 'settle',
    name: 'Settle',
    signal: '(none)',
    meaning: 'Relax and lie quietly, even off the mat.',
    core: false,
    category: 'impulse',
    prerequisites: [],
    teach: [
      'After exercise, sit nearby with his mat down and be boring.',
      'Each time he relaxes, calmly drop a treat between his paws.',
      'Reward longer stretches of calm over time.',
    ],
    mistake: 'Trying to force calm. Capture it instead.',
  },
  {
    id: 'leave-it',
    name: 'Leave it',
    signal: '(none)',
    meaning: 'Do not touch that. Turn away from it.',
    core: true,
    category: 'impulse',
    prerequisites: [],
    teach: [
      'Treat in a closed fist; mark the instant he backs off, pay from the other hand.',
      'Progress to floor under your hand, then open palm, then uncovered.',
      'Add the words once he reliably turns away; proof to dropped food.',
    ],
    mistake: 'Using it only as a panic word. Practice it calmly and often.',
  },
  {
    id: 'off',
    name: 'Off',
    signal: '(none, body block)',
    meaning: 'Four paws on the floor; off the counter or person.',
    core: true,
    category: 'manners',
    prerequisites: [],
    teach: [
      'The moment any paw hits the floor, mark "Yes" and reward low.',
      'You are paying four-on-the-floor.',
      'Never reward while he is still up.',
    ],
    mistake: 'Kneeing or yelling. Just reward four-on-the-floor.',
  },
  {
    id: 'place',
    name: 'Place',
    signal: 'Point to the mat',
    meaning: 'Go to your bed and stay on it.',
    core: true,
    category: 'manners',
    prerequisites: [],
    teach: [
      'Toss a treat onto the mat; when he steps on, mark and treat on the mat.',
      'Add the word "Place", release with "Done", reset off the mat.',
      'Add duration, distance, and kitchen distraction.',
    ],
    mistake: 'Calling him off too soon. This is your counter-surfing workhorse.',
  },
  {
    id: 'drop-it',
    name: 'Drop it',
    signal: '(none)',
    meaning: 'Open your mouth, let it fall.',
    core: true,
    category: 'impulse',
    prerequisites: [],
    teach: [
      'Two-toy game: bring a second toy to life so he drops the first.',
      'Add "drop it" as he opens his mouth; pay every time.',
      'Trade up for treats; never chase or pry his mouth.',
    ],
    mistake: 'Prying his mouth open. Trade instead.',
  },
  {
    id: 'come',
    name: 'Come',
    signal: 'Arms open, or a pat on legs',
    meaning: 'Run to me, fast, all the way.',
    core: true,
    category: 'recall',
    prerequisites: ['name'],
    teach: [
      'Play recall games: ping-pong between people, jackpot each arrival.',
      'Pay it like a jackpot, every time, early on.',
      'Never call to end fun or to do something he dislikes.',
    ],
    mistake: 'Calling to end fun, or calling angry. Never poison this one.',
  },
  {
    id: 'touch',
    name: 'Touch',
    signal: 'Open palm held out',
    meaning: 'Come bump your nose into my hand. A precise recall.',
    core: true,
    category: 'recall',
    prerequisites: [],
    teach: [
      'Present an open palm; mark the nose touch, treat from the other hand.',
      'Add the word, then cue with an empty hand and pay after (never bribe).',
      'Build distance and distractions; take it outside on a long line.',
    ],
    mistake: 'Showing the treat first. Cue with an empty hand, pay after.',
  },
  {
    id: 'collar-grab',
    name: 'Collar grab',
    signal: 'Reach for the collar',
    meaning: 'A hand reaching for the collar predicts a treat.',
    core: false,
    category: 'recall',
    prerequisites: ['touch'],
    teach: [
      'Reach slowly toward his shoulder and feed a treat from the other hand.',
      'Build to touching, then briefly holding, the collar, treating each time.',
      'Have every family member practice from different positions.',
    ],
    mistake: 'Grabbing suddenly, which teaches him to dodge.',
  },
  {
    id: 'emergency-recall',
    name: 'Emergency recall',
    signal: 'A unique word or whistle',
    meaning: 'One sacred cue that always brings him, for emergencies only.',
    core: false,
    category: 'recall',
    prerequisites: ['come'],
    teach: [
      'Pick a word you use for nothing else; charge it with jackpots.',
      'Add coming, then distance on a long line with a sprint backward.',
      'Keep it sacred: it always pays, never ends fun, reserved for emergencies.',
    ],
    mistake: 'Using it casually, which wears it out. Reserve it.',
  },
  {
    id: 'follow-me',
    name: 'Follow me',
    signal: 'Pat your hip',
    meaning: 'Walk next to me on a loose leash.',
    core: false,
    category: 'manners',
    prerequisites: [],
    teach: [
      'Reward him for being at your side, treat at your pant seam.',
      'Stop walking the moment the leash goes tight.',
      'Turn check-ins into a game; pulling never works, staying close pays.',
    ],
    mistake: 'Letting the leash go tight and pulling back.',
  },
]
